import '../styles/globals.css'
import Head from 'next/head'
import { Toaster } from 'react-hot-toast'
import { Navbar } from '../components';
import WorkoutContextProvider from "../context/WorkoutContext"
function MyApp({ Component, pageProps }) {


  return (
   <>
   <WorkoutContextProvider >
   <Head>
        <title>Mern Stack Graphql</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      <Toaster />
    
      <Component {...pageProps} />
      </WorkoutContextProvider>
      </>
  )
}

export default MyApp
